### ISSUE TITLE
Long term support for holochain-runner vs embedded-holochain-runner

### ISSUE THREAD

**Issue by novocodev** [Sprillow/holochain-runner#13]
Hi I have been looking at both embedded-holochain-runner and holochain-runner for wrapping Holochain in a single binary which I want to embed in a container.

I was anticipating that the holochain-runner project would use embedded-holochain-runner internally but it does not look like that is the case?

The repo for holochain-runner has a lot of recent activity whereas embedded-holochain-runner has not seen activity for over a year.

Which solution would you recommend using if long term support/activity is a strong consideration?

**Comment by Connoropolous** [comment]
Hi! 

I would recommend holochain-runner as I felt that it was overkill to have both and decided to merge the code for the embedded one into this repository. We will keep up the maintenance of this library until `holochain` main binary ships with feature parity, if that ever happens. This has some specialized behavior that holochain may never want to implement

**Comment by novocodev** [comment]
Thank you for the reply.
