### ISSUE TITLE
update webrtc_signal_url to wss://signal.holo.host

### ISSUE THREAD

**Issue by Connoropolous** [Sprillow/holochain-runner#22]

**Comment by Connoropolous** [comment]
@kbonnici they have moved the signal server from 'test' to 'production', so we actually want to update this now hahaha

**Comment by Connoropolous** [comment]
can you action this and do a release?

**Comment by Connoropolous** [comment]
I updated the URL in the issue title

**Comment by kbonnici** [comment]
so sorry, just saw this. will do this now.
