### ISSUE TITLE
web-happ support

### ISSUE THREAD

**Issue by novocodev** [Sprillow/holochain-runner#27]
I have started the holochain runner pointing to a web-happ package rather than the happ package.

There are no errors on startup but it does not look like an https port is opened for the front end component.

Is it possible to support web-happ package deployment with the runner?

**Comment by Connoropolous** [comment]
Thanks for logging an issue, I'm curious about your use case.

**Comment by novocodev** [comment]
I'm exploring how I can deploy happs to the cloud

I have containerised holochain-runner as a Docker image

I think it makes sense to package the web UI with the happ so that there are no version mismatches. web-happ looks like a convenient way to package UI and API.

I have created a forum happ following the scaffolding example in the docs and run locally, I am exploring how to achieve something similar with a cloud deployment

I know there is the holo port but this looks like its still a closed ecosystem.

I appreciate cloud deployment goes against the distributed model but it fits with the application I have in mind

**Comment by novocodev** [comment]
Update:

I did not realise that there was a level of happ caching taking place

When I launch Holochain-runner with empty directories and a packaged web-happ the runner process panics

`name = "holochain-runner"
operating_system = "Mac OS 13.4.0 [64-bit]"
crate_version = "0.7.5"
explanation = """
Panic occurred in file 'src/embedded_runner.rs' at line 80
"""
cause = "explicit panic"
method = "Panic"
backtrace = """

   0: 0x1025cbb64 - rust_begin_unwind
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578
   1: 0x10269fd84 - core::panicking::panic_fmt::h324f50b29db90195
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67
   2: 0x10269fdf4 - core::panicking::panic::h0335fbd7add43117
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117
   3: 0x1005d9d68 - holochain_runner::embedded_runner::async_main::{{closure}}::{{closure}}::h98226b6cd7d8790d
   4: 0x10056fdd4 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h5fd1a10a969d83a9
   5: 0x10096b528 - tokio::runtime::task::core::Core<T,S>::poll::he94caa6f710a9f2d
   6: 0x100489f9c - tokio::runtime::task::harness::Harness<T,S>::poll::hf807b9ff80af0e35
   7: 0x1020a169c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h42a76970206c4943
   8: 0x1020a0e04 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hc6a0f5e3d97d757e
   9: 0x10209bf34 - tokio::runtime::context::scoped::Scoped<T>::set::h19949c0f6243a68b
  10: 0x1020a6418 - tokio::runtime::context::runtime::enter_runtime::h6abab6f6a6eaefee
  11: 0x1020a0778 - tokio::runtime::scheduler::multi_thread::worker::run::hed951cde49f3e9e8
  12: 0x102094000 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hc50e5a2a5d580b6c
  13: 0x102098c78 - tokio::runtime::task::core::Core<T,S>::poll::h94a0ae9bde5f987b
  14: 0x102089ea8 - tokio::runtime::task::harness::Harness<T,S>::poll::h82bbaa4f972d79b1
  15: 0x1020b1a9c - tokio::runtime::blocking::pool::Inner::run::h93af5b67fea8c2e8
  16: 0x10209c908 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb132eed3227e622f
  17: 0x10208e7d8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2d2c03e46258991d
  18: 0x1025d03a0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd96d02f907263858
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973
                 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfd80494da4543cfb
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973
                 - std::sys::unix::thread::Thread::new::thread_start::h7f56b35fafcfec87
                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108
  19: 0x19bd33fa8 - __pthread_joiner_wake"""`

**Comment by novocodev** [comment]
This is a low priority for me, I'll use an alternative approach for launching the client, closing out this issue
